language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

env:
  - APP_ENV=testing

before_install:
  - composer self-update

install:
  - composer install --dev
  - npm install

script:
  - node_modules/.bin/gulp
  - bin/phpunit
